# Analyse v${version} - https://analyse.net
# Check out https://analy.se/docs if you need help.

hooks:
  # Enable or disable the plugin's hooks.
  # See https://analyse.net/docs/plugins/bukkit for more information.
  placeholder-api:
    enabled: true
    enabled-stats:
      - 'enter_placeholder_here'

settings:
  # Excluded Players (UUID)
  # Players listed here will not be tracked by Analyse.
  excluded-players: []

  # Minimum Playtime (Seconds)
  # Only track players who have played for at least this amount of time.
  # Set to 0 to disable.
  minimum-playtime: 0

  # Use Server Playtime
  # Use the date the player joined your server as their first session,
  # instead of when they first joined Analyse.
  use-server-playtime: true

server:
  token: ''
  encryption-key: ''

# Which version of the plugin configuration.
# !! Do not change this value !!
config-version: 2